[tool.black]
line-length = 79

[tool.poetry]
name = "oumodulesbot"
version = "0.1.0"
description = ""
authors = ["Jerzy Kozera <jerzy.kozera@gmail.com>"]

[tool.poetry.dependencies]
"discord.py" = "^2.2.3"
python = "^3.11"
pylru = "^1.2.1"
httpx = "^0.24"

[tool.poetry.dev-dependencies]
black = "^22.3"
flake8 = "^6.0"
pytest = "^7"
pytest-asyncio = "^0.18"
mypy = "^1.3.0"
isort = "^5.10"

[build-system]
requires = ["poetry>=1.16.0"]
build-backend = "poetry.masonry.api"
