[tool.black]
line-length = 79

[tool.poetry]
name = "oumodulesbot"
version = "0.1.0"
description = ""
authors = ["Jerzy Kozera <jerzy.kozera@gmail.com>"]

[tool.poetry.dependencies]
"discord.py" = {git = "https://github.com/Rapptz/discord.py", rev = "0bc15fa130b8f01fe2d67446a2184d474b0d0ba7"}
python = "^3.8"
pylru = "^1.2.0"
httpx = "^0.11.1"

[tool.poetry.dev-dependencies]
black = {version = "^19.10b0", allow-prereleases = true}
flake8 = "^3.7.9"
pytest = "^5.3.5"
pytest-asyncio = "^0.10.0"
mypy = "^0.761"
isort = "^4.3.21"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
