[tool.black]
line-length = 79

[tool.poetry]
name = "oumodulesbot"
version = "0.1.0"
description = ""
authors = ["Jerzy Kozera <jerzy.kozera@gmail.com>"]

[tool.poetry.dependencies]
"discord.py" = "^1.7.3"
python = "^3.8"
pylru = "^1.2.0"
httpx = "^0.19"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8"
pytest = "^6"
pytest-asyncio = "^0.14"
mypy = "^0.782"
isort = "^5.5"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
