# based on https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runner
name: Docker Serverless Base Image CI

on:
  push:
    branches: [ main ]
    paths:
      - cloudfunctions-cc/Dockerfile.base

env:
  REGISTRY_IMAGE: stemclubmodulesbot/cloudfunctions-cc-base

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Build
        id: build
        uses: docker/build-push-action@v6
        with:
          context: cloudfunctions-cc
          file: cloudfunctions-cc/Dockerfile.base
          push: true
          tag: ${{ env.REGISTRY_IMAGE }}:latest
