name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.CI_REGISTRY_IMAGE }}:latest
    - name: Push the image to registry
      run: docker login -u ${{ secrets.CI_REGISTRY_USER }} -p ${{ secrets.CI_REGISTRY_PASSWORD }} &&
           docker push ${{ secrets.CI_REGISTRY_IMAGE }}:latest
      if: ${{ github.event_name == 'push' }}
