name: lint and test the code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install-dependencies
    - name: Lint with isort
      run: |
        poetry run isort -c .
    - name: Lint with flake8
      run: |
        poetry run flake8 .
    - name: Lint with black
      run: |
        poetry run black --check .
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install-dependencies
    - name: Check with mypy
      run: |
        poetry run mypy .
  tests:
    runs-on: ubuntu-latest
    needs: [lint, mypy]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install-dependencies
    - name: Run tests
      run: |
        poetry run pytest tests
