name: lint and test the code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry install
    - name: Lint with flake8
      run: |
        poetry run flake8 .
    - name: Lint with black
      run: |
        poetry run black --check .
    - name: Run tests
      run: |
        poetry run pytest tests
